# Generated by Django 3.2.18 on 2023-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0003_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('food_type', models.CharField(choices=[('Meat', 'Meat'), ('Bread', 'Bread'), ('Pastry', 'Pastry'), ('Fruit', 'Fruit'), ('Vegan', 'Vegan'), ('Drinks', 'Drinks')], default='Meat', max_length=25, verbose_name='Food type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
