# Generated by Django 3.2.18 on 2023-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='food_type',
            field=models.CharField(choices=[('meat', 'meat'), ('Bread', 'Bread'), ('Pastry', 'Pastry'), ('Fruit', 'Fruit'), ('Vegan', 'Vegan'), ('Drinks', 'Drinks')], default='meat', max_length=25, verbose_name='Food type'),
        ),
    ]
