# Generated by Django 3.2.18 on 2023-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0005_alter_item_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='food_type',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Bread', 'Bread'), ('Pastry', 'Pastry'), ('Fruit', 'Fruit'), ('Vegan', 'Vegan'), ('Drinks', 'Drinks')], default='Meat', max_length=25, verbose_name='food_type'),
        ),
    ]
