# Generated by Django 3.2.18 on 2023-04-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0007_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, choices=[('MBD', 'MASTERBEDROOM'), ('BD2', 'BEDROOM2')], max_length=3, null=True),
        ),
    ]
