# Generated by Django 3.2.18 on 2023-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0008_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, choices=[('MBD', 'Master Bedroom'), ('BD2', 'Second Bedroom')], max_length=3, null=True),
        ),
    ]
