# Generated by Django 3.2.18 on 2023-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0009_alter_room_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoomTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_type', models.CharField(choices=[('Master Bedroom', 'Master Bedroom'), ('Queen Bedroom', 'Queen Bedroom')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, choices=[('Master Bedroom', 'Master Bedroom'), ('Queen Bedroom', 'Queen Bedroom')], max_length=50, null=True),
        ),
    ]
