# Generated by Django 3.2.18 on 2023-04-27 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0010_auto_20230422_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRoomTest',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=datetime.date(2023, 5, 21)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=datetime.date(2023, 5, 28)),
        ),
    ]
